### ISSUE TITLE
Github repository meta documents missing

### ISSUE THREAD

**Issue by YashKumarVerma** [coding-blocks/judge-taskmaster#38]
The following documents are missing and should be added to validate the open source project and structure a community.

- [x] Pull Request Template
- [x] Issue Template
- [x] Contributing Guidelines
- [x] Code Of conduct

Working on it, claiming.

**Comment by YashKumarVerma** [comment]
pinging for bounty triage @hereisnaman

**Comment by jatinkatyal13** [comment]
Sure ! Go Ahead
